### ISSUE TITLE
Column dissappears on iphone

### ISSUE THREAD

**Issue by techbo1337** [axe312ger/gatsby-mdx-suite#137]
I've used the following layout:

`<Columns>
  <Column backgroundImageId="xx"></Column>
  <Column>Text</Column>
</Columns>`

On iPhone the first <Column /> disappeared.

**Comment by axe312ger** [comment]
We should add the minimumAspectRatio property from Box to Column. That way we can ensure a minimum size when using a background image.

**Comment by axe312ger** [comment]
@techbo1337 please try to use the minAspectRatio attribute
